### ISSUE TITLE
No method to create dedicated virtual account

### ISSUE THREAD

**Issue by GeekyGeeky** [en1tan/paystack-node#1]
I have looked through the docs and found no method to create a dedicated virtual account(NUBAN), please can you point me to its location if available.

**Comment by en1tan** [comment]
I have not had time to update the package but PRs are welcome🙌

**Comment by en1tan** [comment]
@GeekyGeeky 73f355d02430306b28a57b97c6a553695a2c7d26
updated

**Comment by GeekyGeeky** [comment]
Thank you for your quick response, I look forward to future contributions

**Comment by GeekyGeeky** [comment]
Please don't forget to publish latest version on npm

**Comment by en1tan** [comment]
I have, check v1.1.20

**Comment by GeekyGeeky** [comment]
> > Thank you for your quick response, I look forward to future contributions
> 
> I have, check v1.1.20

Thanks, seen it. Great work
