### ISSUE TITLE
Creating dedicated Nuban is throwing an error

### ISSUE THREAD

**Issue by GeekyGeeky** [en1tan/paystack-node#2]
I noticed an error when I tried to create a dedicated nuban, I fixed it but I am unable to make a PR. kindly help check it out or allow PRs to be made.
Thanks

The error below
Error: Data after transformation must be a string, an ArrayBuffer, a Buffer, or a Stream

**Comment by en1tan** [comment]
I will check it

**Comment by GeekyGeeky** [comment]
Thank you. Great job man

**Comment by GeekyGeeky** [comment]
Hi there, has the issue been resolved

**Comment by orimdominic** [comment]
@GeekyGeeky Is there any reason why you are unable to make a PR?

**Comment by en1tan** [comment]
I have been really busy and not able to look at it, honestly PRs are welcome

**Comment by GeekyGeeky** [comment]
Been trying to push a PR but unable to do that, I'll try again.

**Comment by GeekyGeeky** [comment]
@orimdominic the data sent should be sent as JSON string, that should fix it.

**Comment by orimdominic** [comment]
@GeekyGeeky You can probably paste the stacktrace of the error here or the steps (the file(s) that you modified and the code that you changed) here and I'll make a PR

**Comment by GeekyGeeky** [comment]
Ok no problem. Thanks

**Comment by GeekyGeeky** [comment]
I just tried making the PR again, made a fix

**Comment by GeekyGeeky** [comment]
hello @en1tan , please kindly review the PR. 
Thanks

**Comment by en1tan** [comment]
merged and published. thank you
